SRC=src/test.c src/bubble.c src/insertion.c src/merge.c src/vector.c src/selection.c src/shell.c
INCLUDE=./include
COMPILER=gcc
BINARY=t



all:
	$(COMPILER) $(SRC) -I$(INCLUDE) -o $(BINARY) -O2
	./$(BINARY)

