SRC=src/test.c src/bubble.c src/insertion.c src/merge.c src/vector.c src/selection.c src/shell.c src/quick.c src/utils.c src/heap.c src/counting.c
INCLUDE=./include
COMPILER=gcc
BINARY=t



all:
	$(COMPILER) $(SRC) -I$(INCLUDE) -o $(BINARY) -O2
	./$(BINARY)

